//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobManagementSystem.Common.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CategoryResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JobManagementSystem.Common.Resources.CategoryResource", typeof(CategoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        public static string CreateAt {
            get {
                return ResourceManager.GetString("CreateAt", resourceCulture);
            }
        }
        
        public static string CreatBy {
            get {
                return ResourceManager.GetString("CreatBy", resourceCulture);
            }
        }
        
        public static string UpdateAt {
            get {
                return ResourceManager.GetString("UpdateAt", resourceCulture);
            }
        }
        
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        public static string UpdateBy {
            get {
                return ResourceManager.GetString("UpdateBy", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        public static string TitleIndex {
            get {
                return ResourceManager.GetString("TitleIndex", resourceCulture);
            }
        }
        
        public static string TitleDetails {
            get {
                return ResourceManager.GetString("TitleDetails", resourceCulture);
            }
        }
        
        public static string TitleCreate {
            get {
                return ResourceManager.GetString("TitleCreate", resourceCulture);
            }
        }
        
        public static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
        
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        public static string BtnCreate {
            get {
                return ResourceManager.GetString("BtnCreate", resourceCulture);
            }
        }
        
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        public static string BtnDetails {
            get {
                return ResourceManager.GetString("BtnDetails", resourceCulture);
            }
        }
        
        public static string BtnLock {
            get {
                return ResourceManager.GetString("BtnLock", resourceCulture);
            }
        }
        
        public static string BtnUnlock {
            get {
                return ResourceManager.GetString("BtnUnlock", resourceCulture);
            }
        }
        
        public static string RadioTrue {
            get {
                return ResourceManager.GetString("RadioTrue", resourceCulture);
            }
        }
        
        public static string RadioFalse {
            get {
                return ResourceManager.GetString("RadioFalse", resourceCulture);
            }
        }
        
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        public static string BtnBackToList {
            get {
                return ResourceManager.GetString("BtnBackToList", resourceCulture);
            }
        }
        
        public static string HomeAdmin {
            get {
                return ResourceManager.GetString("HomeAdmin", resourceCulture);
            }
        }
        
        public static string UrlCategory {
            get {
                return ResourceManager.GetString("UrlCategory", resourceCulture);
            }
        }
        
        public static string UrlIndex {
            get {
                return ResourceManager.GetString("UrlIndex", resourceCulture);
            }
        }
        
        public static string UrlDetail {
            get {
                return ResourceManager.GetString("UrlDetail", resourceCulture);
            }
        }
        
        public static string UrlEdit {
            get {
                return ResourceManager.GetString("UrlEdit", resourceCulture);
            }
        }
        
        public static string UrlCreate {
            get {
                return ResourceManager.GetString("UrlCreate", resourceCulture);
            }
        }
        
        public static string placeholderCategoryName {
            get {
                return ResourceManager.GetString("placeholderCategoryName", resourceCulture);
            }
        }
        
        public static string Statusfalse {
            get {
                return ResourceManager.GetString("Statusfalse", resourceCulture);
            }
        }
        
        public static string StatusTrue {
            get {
                return ResourceManager.GetString("StatusTrue", resourceCulture);
            }
        }
        
        public static string TitleCategoryIndex {
            get {
                return ResourceManager.GetString("TitleCategoryIndex", resourceCulture);
            }
        }
        
        public static string TitleCategoryDetail {
            get {
                return ResourceManager.GetString("TitleCategoryDetail", resourceCulture);
            }
        }
        
        public static string TitleCategoryEdit {
            get {
                return ResourceManager.GetString("TitleCategoryEdit", resourceCulture);
            }
        }
        
        public static string TitleCategoryCreate {
            get {
                return ResourceManager.GetString("TitleCategoryCreate", resourceCulture);
            }
        }
    }
}
